### ISSUE TITLE
Suggestion of two DUNE papers

### ISSUE THREAD

**Issue by lhwhitehead** [iml-wg/HEPML-LivingReview#102]
Dear all,

Firstly, thanks for this nice project - I'm not sure how I haven't come across it before! I noticed that our DUNE neutrino classifier paper from 2020 isn't included.
@article{DUNE:2020gpm,
    author = "Abi, B. and others",
    collaboration = "DUNE",
    title = "{Neutrino interaction classification with a convolutional neural network in the DUNE far detector}",
    eprint = "2006.15052",
    archivePrefix = "arXiv",
    primaryClass = "physics.ins-det",
    reportNumber = "FERMILAB-PUB-20-241-E",
    doi = "10.1103/PhysRevD.102.092003",
    journal = "Phys. Rev. D",
    volume = "102",
    number = "9",
    pages = "092003",
    year = "2020"
}

There is also a new paper from ProtoDUNE-SP on the separation of track- and shower-like hits that has appeared on the arXiv:
@article{DUNE:2022fiy,
    author = "Abed Abud, Adam and others",
    collaboration = "DUNE",
    title = "{Separation of track- and shower-like energy deposits in ProtoDUNE-SP using a convolutional neural network}",
    eprint = "2203.17053",
    archivePrefix = "arXiv",
    primaryClass = "physics.ins-det",
    reportNumber = "FERMILAB-PUB-22-240-AD-ESH-LBNF-ND-SCD, CERN-EP-2022-077",
    month = "3",
    year = "2022"
}

I think the neutrino detectors section is the best place for these.

Kind Regards,

Leigh

**Comment by bnachman** [comment]
Hi @lhwhitehead thank you for pointing out these papers!  Would you be able to add them following the instructions here: https://github.com/iml-wg/HEPML-LivingReview/blob/master/CONTRIBUTING.md?  We are happy to help if you run into any issues.  

Sincerely,
Ben

**Comment by lhwhitehead** [comment]
Hi Ben,

I think I've done things correctly and made this pull request: https://github.com/iml-wg/HEPML-LivingReview/pull/103

Kind Regards,
Leigh

**Comment by lhwhitehead** [comment]
Just wanted to check that the pull request looks ok?
