### ISSUE TITLE
Jet Energy Corrections with GNN Regression

### ISSUE THREAD

**Issue by deinal** [iml-wg/HEPML-LivingReview#106]
Hi, 

I studied how to improve jet energy corrections with graph neural network regression and figured it could be useful addition to this list of ML litterature. It uses modified versions of Particle Flow Network and ParticleNet for the corrections, both of which are found in the list under ML for point clouds.

My contribution fits under `Regression` -> `Calibration`. As far as I can see it's the first of its kind in the list that utilizes set based / graph based deep learning for energy calibration. If it looks alright I can open a PR for it.

Link: https://helda.helsinki.fi/handle/10138/344118

(Presentation: https://indico.ijclab.in2p3.fr/event/5999/timetable/#32-jet-energy-corrections-with)

**Comment by ramonpeter** [comment]
Hi @deinal,
Is there also a published version of this which is either on Arxiv or within a peer-reviewed journal?
Right now we only provide a collection of research works that are published.

However, there has already been a discussion about potentially adding a dedicated section about PhD theses, if they cover topics not already being published before.

**Comment by deinal** [comment]
Hi @ramonpeter, there will be a published version in Software and Computing for Big Science. I can ping you here once it is live.

**Comment by ramonpeter** [comment]
Hey @deinal, can you provide a proper bibtex item so that we can incorporate it?

**Comment by deinal** [comment]
For sure, here you go @ramonpeter
```
@article{Holmberg:2023,
    author = {Holmberg, Daniel and Golubovic, Dejan and Kirschenmann, Henning},
    title = "{Jet Energy Calibration with Deep Learning as a Kubeflow Pipeline}",
    journal = {Computing and Software for Big Science},
    year = {2023},
    month = {Aug},
    day = {23},
    volume = {7},
    number = {1},
    pages = {9},
    issn = {2510-2044},
    doi = {10.1007/s41781-023-00103-y}
}
```

**Comment by ramonpeter** [comment]
Done with small adjustments in the bibtex entry. See #182
