### ISSUE TITLE
Add a new paper

### ISSUE THREAD

**Issue by rutepedro** [iml-wg/HEPML-LivingReview#11]
Hello,

We would like to add a recent pre-print on unsupervised learning:
"Use of a Generalized Energy Mover's Distance in the Search for Rare Phenomena at Colliders", https://arxiv.org/abs/2004.09360

Best regards,
Rute Pedro

**Comment by matthewfeickert** [comment]
This was already added to [HEP-ML-Resources in PR 75](https://github.com/iml-wg/HEP-ML-Resources/pull/75) and so will get migrated over eventually with all the others.
