### ISSUE TITLE
Year in paper titles would be great

### ISSUE THREAD

**Issue by Crashtime** [iml-wg/HEPML-LivingReview#112]
Hello, thank you for constructing and maintaining this, our field needs it! 

Would it be possible to include the year of the paper in the titles? I can add the years my self for what is there already.

Cheers

**Comment by matthewfeickert** [comment]
> Would it be possible to include the year of the paper in the titles? 

I'm -1 on this at the moment as I don't think this really adds much value in general and just adds in more metadata to something that is meant to be a simple listing and not a replication and not another database &mdash; we have INSPIRE for that.

If this was going to be implimented it would make more sense to revamp the project as a proper generated website and have this information just get grabbed from the INSPIRE API.

Can you elaborate on why you want the paper years in the title?

**Comment by Crashtime** [comment]
I understand! Thanks for the effort! It would be to be able to understand
directly how recent the publications are. I am not a great website builder
but I can write the code to get the info from the inspire api.

Cheers,
João Pedro de Arruda Gonçalves


Matthew Feickert ***@***.***> escreveu no dia sábado,
9/07/2022 à(s) 14:21:

**Comment by bnachman** [comment]
I would be in favor of adding this, as I think it is nice to know the timescale.  The papers are supposed to be ordered in time, but it can be nice to know how old certain papers are.  @Crashtime would you be able to add this?  I think it should be easy to grab from the existing metadata.   We don't have to be super precise about arXiv date versus published date.

**Comment by Crashtime** [comment]
Thanks Ben! The distribution in time could be useful to see even if the
papers are in chronological order. I can play around with the API and add
this over this week. I would use the arxiv date if you agree.

**Comment by bnachman** [comment]
Great, thanks!  arXiv date makes sense to me.

**Comment by Crashtime** [comment]
Hello,

I have made some alterations to the make_md.py file and was able to include
the year, without the need for the arxiv API.

I created a new branch and would like to push it to the repo and follow
with a merge request, is this possible?

Cheers,
João Pedro de Arruda Gonçalves


Ben Nachman ***@***.***> escreveu no dia segunda, 11/07/2022
à(s) 00:59:

**Comment by ramonpeter** [comment]
Hi,

I think you never send a PR, did you?
Can you make the PR as explained in CONTRIBUTING.md? I can review it then.
Thanks

**Comment by cspollard** [comment]
Hi. I was about to open an issue on the same topic but will +1 here instead. Knowing when a paper was posted (even just the year) would really help identify which are most likely to be useful!

**Comment by ramonpeter** [comment]
Hi,
in general, all paper are sorted chronologically. This means the oldest are on top and the newest at the bottom.
However, I agree that having a simple (year) behing might be helpful.

**Comment by ramonpeter** [comment]
Done and included since #226

**Comment by Crashtime** [comment]
Hi,
This is very nice thank you and apologies for my low reply rate.
