### ISSUE TITLE
Clarify that collaboration papers should have author be collabortation name

### ISSUE THREAD

**Issue by matthewfeickert** [iml-wg/HEPML-LivingReview#151]
> This is ... and doesn't follow the instructions of the `CONTRIBUTING.md` :
> 
> ```
> Get the BibTeX for the paper citation provided by INSPIRE (under "Export" at the bottom of the page)
> 
> Add this BibTeX entry to [HEPML.bib](https://github.com/iml-wg/HEPML-> LivingReview/blob/master/HEPML.bib) in the appropriate chronological position
> ```

_Originally posted by @mattleblanc in https://github.com/iml-wg/HEPML-LivingReview/pull/149#discussion_r1211208147_

**Comment by claudius-krause** [comment]
Could changing the author to the collaboration cause any problems with different bib-style bst files?

**Comment by matthewfeickert** [comment]
> Could changing the author to the collaboration cause any problems with different bib-style bst files?

Not that I know of. We do this in ATLAS anyway for all of the ATLAS BibTeX files for papers and notes, and I had been doing it from the start on citations I added and no one has complained so far.

**Comment by jraine** [comment]
Would you suggest to have it done by hand each time, or might it be worth adding to the CI to find instances of this and automatically update them as well?

The expression would be
`author\s+=\s+"[^"]+",\r?\n\s+collaboration\s+=\s+"([^"]+)",`
to find the collaboration name and then replace the whole thing with
`author = "\{$1 Collaboration\}",`

**Comment by claudius-krause** [comment]
Solved with PR #161
