### ISSUE TITLE
Add Machine and Deep Learning Applications in Particle Physics review paper

### ISSUE THREAD

**Issue by bourilkov** [iml-wg/HEPML-LivingReview#16]
Hi,

Please add a new ML review paper:

Machine and Deep Learning Applications in Particle Physics
Dimitri Bourilkov (Florida U.)
Dec 17, 2019
30 pages
Published in: Int.J.Mod.Phys.A 34 (2019) 35, 1930019
e-Print: 1912.08245 [physics.data-an]
DOI: 10.1142/S0217751X19300199

```
@article{Bourilkov:2019yoi,
    author = "Bourilkov, Dimitri",
    title = "{Machine and Deep Learning Applications in Particle Physics}",
    eprint = "1912.08245",
    archivePrefix = "arXiv",
    primaryClass = "physics.data-an",
    doi = "10.1142/S0217751X19300199",
    journal = "Int. J. Mod. Phys. A",
    volume = "34",
    number = "35",
    pages = "1930019",
    year = "2019"
}
```

https://inspirehep.net/literature/1771528

Thanks,
Dimitri

**Comment by matthewfeickert** [comment]
@bourilkov Thanks for the reference. We can add this tonight, or if you have time now you can open a PR for it yourself (c.f. instructions in [`CONTRIBUTING.md`](https://github.com/iml-wg/HEPML-LivingReview/blob/master/CONTRIBUTING.md)).
