### ISSUE TITLE
Curly braces not removed from the doi field

### ISSUE THREAD

**Issue by deinal** [iml-wg/HEPML-LivingReview#183]
**Issue Description**

The current BibTeX parser fails to remove curly braces `{` and `}` from the `doi` field in the parsed output. 

E.g. entry `DCTRGAN: Improving the Precision of Generative Models with Reweighting` gets the following doi address `https://doi.org/%7B10.1088/1748-0221/15/11/p11004` because it has doi with curly braces [in HEPML.bib](https://github.com/iml-wg/HEPML-LivingReview/blob/4ed28e617e7384dce1244a6c2809eb1ca6ab6a8e/HEPML.bib#L8781C7-L8781C46). The `%7` character suggests that the first curly brace is not removed.

For entry `Jet Energy Calibration with Deep Learning as a Kubeflow Pipeline` both opening and closing curly braces are left in the url produced by make_md.py: `https://www.doi.org/%7B10.1007/s41781-023-00103-y%7D`. The difference as we can see from [here](https://github.com/iml-wg/HEPML-LivingReview/blob/4ed28e617e7384dce1244a6c2809eb1ca6ab6a8e/HEPML.bib#L15C5-L15C39) is that this entry doesn't have a trailing comma at the end of the line like DCTRGAN does.

**Suggested Fix**

I believe a fix could be introduced [here](https://github.com/iml-wg/HEPML-LivingReview/blob/master/make_md.py#L108) in the parser code to remove the curly braces from the doi field.

```python
if "{" in myentry_dict["doi"]:
    myentry_dict["doi"] = myentry_dict["doi"][1:]
if "}" in myentry_dict["doi"]:
    myentry_dict["doi"] = myentry_dict["doi"][:-1]
```

A similar thing is done for the opening bracket in `myentry_dict["eprint"]` a few lines earlier.

**Comment by ramonpeter** [comment]
Fixed with #229
