### ISSUE TITLE
missing ref to 2015 "Playing Tag with ANN: Boosted Top Identification with Pattern Recognition"

### ISSUE THREAD

**Issue by vlimant** [iml-wg/HEPML-LivingReview#26]
https://arxiv.org/abs/1501.05968
I might make a PR later

**Comment by bnachman** [comment]
Added!  Thank you @vlimant for catching that missing reference.

**Comment by matthewfeickert** [comment]
Closed by e14991621ec626484b05f8641c347af0f0a0890f
