### ISSUE TITLE
Adding references 

### ISSUE THREAD

**Issue by kcharanj** [iml-wg/HEPML-LivingReview#34]
Hi Matthew, 
Could you please include arXiv:1902.05803, 1911.09210 and 1910.06058 [hep-ph] ?

Many thanks.

Best regards,
Charanjit

**Comment by bnachman** [comment]
Added.  Thank you @kcharanj!

**Comment by matthewfeickert** [comment]
Closed by 83d02a94b17ad62d0ec6822c6b537bb2729c515d
