### ISSUE TITLE
@inproceedings entries use booktitle instead of title

### ISSUE THREAD

**Issue by jmduarte** [iml-wg/HEPML-LivingReview#45]
Currently, `@inproceedings` type entries appear on the webpage with the conference name (`booktitle`) instead of the `title` of the paper.

See, e.g.

<img width="724" alt="Screen Shot 2021-01-22 at 7 58 40 PM" src="https://user-images.githubusercontent.com/4932543/105568169-3b307200-5cec-11eb-955a-7b7d25e7a348.png">

**Comment by bnachman** [comment]
I have changed all of the @inproceedings to @article (and added "journal" when possible) ... I hope this fixes it! Thank you @jmduarte

**Comment by matthewfeickert** [comment]
Closed by ae13060
