### ISSUE TITLE
updating .bib

### ISSUE THREAD

**Issue by cranmer** [iml-wg/HEPML-LivingReview#5]
As papers get accepted to journals and conferences we would like to update the .bib file. In my experience, people are not good about updating this kind fo thing, but it's easy to automate it.

I think it would be nice to just have a list of inspire IDs and then hit the API to build the page and build an up-to-date. bib file (similar to what we do for IRIS-HEP web page)

**Comment by dguest** [comment]
To repeat the question I asked in IML here: for experiment papers, do we want to use what we get out of INSPIRE or should we use what experiments recommend? 

ATLAS, for example, maintains bibliography files for ATLAS that they recommend everyone use. This isn't aligned with what INSPIRE provieds, but I would assume that everyone should respect the experiment's conventions when citing their papers.

**Comment by matthewfeickert** [comment]
> or should we use what experiments recommend?

I was thinking about this the other night. I agree that if possible we should try to adhere to what the experiments recommend, especially as it fixes this "<Experiment Name> Collaboration Collaboration" nonsense that pops up from using the default INSPIRE entries. Off the top of my head I'm not sure how to achieve this though.

**Comment by dguest** [comment]
To first order we can just copy the ATLAS bib file into this, no?

**Comment by matthewfeickert** [comment]
> To first order we can just copy the ATLAS bib file into this, no?

This would work, but @cranmer [had pointed out](https://github.com/iml-wg/HEPML-LivingReview/issues/4#issue-609343701) that if possible it would be a good idea to try to move to an automated workflow. Which is the problem. But I agree that getting things in there correctly _now_ would be an important first step.

> It would be great if that prompted CMS and other experiments to do the same

:100:% agree.

**Comment by bnachman** [comment]
Hi @dguest,

I am not sure we necessarily need to agree to cite papers the way ATLAS and CMS want them to be cited.  For example, ATLAS wants the "D" in Phys. Rev. D to be part of the journal name and not the volume.  This is not how Inspire does it by default (I don't know what CMS does).  We still need to work out a system for updating papers but I think we should try to use Inspire as the standard when possible.  For collaborations, we can of course use those names instead of the authors as I think the experiments would request.

Sincerely,
Ben

**Comment by dguest** [comment]
I think we can use ATLAS standards for ATLAS papers, no?

**Comment by dguest** [comment]
I think it's _mostly_ a moot point though: most of the experimental papers are probably not listed on INSPIRE anyway.

**Comment by bnachman** [comment]
For PUB/CONF, we should definitely use the ATLAS standards.   For journal publications, I don't see why we should use a different style for ATLAS papers and non-ATLAS papers.  Why Phys. Rev. D **23** for an ATLAS paper and Phys. Rev. **D23** for a non-ATLAS paper?   People will want a harmonized style.

**Comment by dguest** [comment]
that's true about the journal name. For other useful data we might want to look into something like this: 

https://github.com/FlamingTempura/bibtex-parse

not sure how well it works but if we convert the bib data to something more python friendly it might be possible to merge things.

**Comment by bnachman** [comment]
Hi @dguest that script looks incredibly useful!

**Comment by cranmer** [comment]
Hi all

This is the perfect time to give feedback to INSPIRE about the problems. INSPIRE isn't a static entity, we can point out problems like the "Collaboration Collaboration" issue. My memory is that is a clash between the bibstyle and the .bib itself. Do we have some examples or more info on that?

**Comment by cranmer** [comment]
Conf notes *are* on INSPIRE

https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=find%20r%20atlas-conf-%2A

https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=find%20r%20cms-pas-%2A

https://blog.inspirehep.net/2012/12/httpblog-inspirehep-net201212confronting-those-confounding/

**Comment by bnachman** [comment]
Hi @cranmer,

I don't think INSPIRE catalogs PUB notes (or DP notes as CMS calls them)?

Sincerely,
Ben

**Comment by cranmer** [comment]
It looks like they have the CMS PAS and CMS DP notes:
https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=find%20r%20cms-dp-%2A

They have some ATLAS-PHYS-* notes but not ATLAS-PHYS-PUB for some reason. But again, this can all be revisited, INSPIRE isn't a static entity, they respond to user requests.

Either way, the CONF notes, PAS, DP notes are the majority. ATLAS doesn't have very many pub notes, and they can be handled in a different way if needed.

**Comment by bnachman** [comment]
Great - glad to see the DP notes are in there!  I agree there are not many PUB notes, though of the notes relevant for ML, there is an increased rate of PUB over CONF.   I have made a suggestion on the INSPIRE website to include PUB notes.

**Comment by cranmer** [comment]
It may be something we have to bring up with ATLAS publication committee as well.

**Comment by dguest** [comment]
I actually contacted INSPIRE about the author list point (how ATLAS prefers to be have the authors listed as "ATLAS Collaboration"). Their response was something along the lines of a bib file being more of a database: the fields are just data that you can arrange as you like.

I'm sympathetic to that point but I don't see how to work with it in practice. You could probably come up with a bib style that would list the collaboration as the "author", but good luck getting people to use it...

**Comment by cranmer** [comment]
In the model where we use inspire API we can just do that ourselves and map
the collaboration field into an author field. We don’t have to get raw .bib
we can get JSON for the full record. Also allows us to clean / replace some
latex symbols (Eg ones in define statements) if we need to.

Kyle

**Comment by bnachman** [comment]
Hello,

The make_md.py now automatically synchs with Inspire to get the journal information.  Thank you @cranmer for your inspirational script at https://github.com/cranmer/inspire_play.  I was initially stumped because we have many records with arXiv numbers but no inspire numbers - turns out (probably you know this already) that one can query the Inspire api directly with the arXiv number!  In any case, feedback on this is most welcome!

Sincerely,
Ben
