### ISSUE TITLE
Several papers on heavy ion physics

### ISSUE THREAD

**Issue by duyilun** [iml-wg/HEPML-LivingReview#52]
Hi, 

Many thanks to the authors for launching this project, which is very useful to the HEPML community. Here I have two comments on three papers in the section of **heavy ion physics**: 

1. The paper [Identifying the nature of the QCD transition in relativistic collision of heavy nuclei with deep learning](https://link.springer.com/article/10.1140%2Fepjc%2Fs10052-020-8030-7) (DOI), [arXiv:1910.11530 [hep-ph]](https://arxiv.org/abs/1910.11530) is **not yet** on the list so far. It serves as a follow-up paper of the one [An EoS-meter of QCD transition from deep learning](https://www.nature.com/articles/s41467-017-02726-3) (DOI), whose DOI could also be added.  Both works mainly take **event images** as input to CNN.

2.  The paper [Deep learning jet modifications in heavy-ion collisions](https://arxiv.org/abs/2012.07797) (arXiv:2012.07797) is actually a regression task instead of a classification one. It takes **jet images** as input to CNN. In this work we also make a lot of effort in the **interpretability** of this task by training physics-inspired observables with fully-connected networks in parallel.

**Comment by bnachman** [comment]
Hi @duyilun thank you for your contribution!  I have integrated these into the review.  Please let me know if it is not what you had in mind (I left 2012.07797 also in classification so that it is also cross-linked under HI).

**Comment by duyilun** [comment]
Thanks for your work and consideration!
