### ISSUE TITLE
Escaping of `{}` in eprint fields error

### ISSUE THREAD

**Issue by matthewfeickert** [iml-wg/HEPML-LivingReview#70]
In PR #69 there's an example from @alexverus where the `eprint` for reference

https://github.com/iml-wg/HEPML-LivingReview/blob/94bb393bb35d0d6bd2bfddf364a733edaad462c6/HEPML.bib#L3051-L3058

is not being properly escaped and results in 

```
https://arxiv.org/abs/{1804.09720
```

**Comment by bnachman** [comment]
Hi @matthewfeickert I just put in a quick fix for this - hopefully it is okay now.  Please close if you are satisfied with it.

**Comment by matthewfeickert** [comment]
Thanks @bnachman. LGTM.

**Comment by matthewfeickert** [comment]
Resolved by 5086048f302fb2de4c6c5fd8c5863c0fddd83e4c
