### ISSUE TITLE
Where does Object Condensation go

### ISSUE THREAD

**Issue by jkiesele** [iml-wg/HEPML-LivingReview#72]
Hi all together,

first of all, I think this is an excellent project! Thank you for starting and maintaining it!
In the spirit of contributing I wanted to add my Object Condensation paper [https://arxiv.org/abs/2002.03605] to the list, but I am a bit confused which category it would fit into. 
In short: it is a training method for predicting an unknown number of objects from an unknown number of inputs, including their properties. The method is not bound to the objects being dense or having defined bounding boxes (e.g. no classical NMS possible). It is showcased on a simple image example, but also applied to a particle flow problem, and compared to the CMS particle flow in a simplified setting using graph networks.
So it is not just classification, it clearly graph-network related though, it has something to do with reconstruction in general, and in principle touches on tracking, too.

Since you had a structure in mind designing the categories, do you have a suggestion where it should go?

Best,
Jan

**Comment by bnachman** [comment]
Hi @jkiesele thank you for your kind words and thank you for contributing!  Your work is very interesting and I agree it is not completely obvious where it belongs.  For now, I put it under regression/calibration, but please feel free to reopen and suggest an alternative categorization.  Please note that it is also fine for one paper to be listed under multiple categories.

**Comment by jkiesele** [comment]
Hi Ben,

Thanks :)
I might get to it in the next days if I find some time.

Best,
Jan

On 1 Aug 2021, at 21:25, Ben Nachman ***@***.******@***.***>> wrote:



Hi @jkiesele<https://github.com/jkiesele> thank you for your kind words and thank you for contributing! Your work is very interesting and I agree it is not completely obvious where it belongs. For now, I put it under regression/calibration, but please feel free to reopen and suggest an alternative categorization. Please note that it is also fine for one paper to be listed under multiple categories.
