### ISSUE TITLE
Add NNPDF code and results

### ISSUE THREAD

**Issue by Zaharid** [iml-wg/HEPML-LivingReview#80]
Hello! We have just publised the NNPDF 4.0 determination of Parton Distribution Functions, which uses neural networks to determine PDFs and is described in

https://arxiv.org/abs/2109.02653

and made the code and full dataset publicly available here

https://github.com/NNPDF/nnpdf

together with a companion paper describing it here

https://arxiv.org/abs/2109.02671

I would be grateful if these could be added at least under:

Parton Distribution Functions (and related)

and perhaps also under Uncertainty Quantification/Estimation.

I am opening an issue as per the contribution guidelines, and would be happy to add a PR as well.

**Comment by matthewfeickert** [comment]
@Zaharid looks great! (As an aside, I think it is fantastic too that you have the code on Zenodo and that you linked the code in the arXiv paper's "Code & Data" tab. :rocket:) Please open a PR if you're willing to and if you don't have time let me know and we can open one.

**Comment by Zaharid** [comment]
Thank you @matthewfeickert. Please see #81.
