### ISSUE TITLE
Paper about using GAN to generater parameter samples

### ISSUE THREAD

**Issue by wk-mike** [iml-wg/HEPML-LivingReview#91]
Hi,

Thank you so much for launching this project, which is very useful. Could you please include this paper arXiv:2002.05554 [hep-ph] ?

The paper "A Novel Scenario in the Semi-constrained NMSSM" developed a novel efficient scan method, where the **GAN** can generate a huge amount of recommended samples in a short time. With this efficient method, we find a new scenario in a SUSY model.

DOI: https://doi.org/10.1007/JHEP06(2020)078
arXiv: https://arxiv.org/abs/2002.05554
Inspire: https://inspirehep.net/literature/1780130

Many thanks.

Best,

Mike

**Comment by matthewfeickert** [comment]
Thanks for the paper suggestion @wk-mike. We'll get to this later when we have time, but if you have the time and the interest you should also feel free to take a look over the [`CONTRIBUTING.md`](https://github.com/iml-wg/HEPML-LivingReview/blob/2b742d0cc5c537a432c3b6a66af7a072ce7c0dff/CONTRIBUTING.md#pull-request-process) guidelines and beat us to it. :slightly_smiling_face: Contributions are always very welcome, but even Issues like this help.

**Comment by wk-mike** [comment]
Thank you very much.  I am very glad to contribute.   
I have tied to give a Pull request,  and I hope I did it right. 
If the Pull request is OK, we can close this issue.
@matthewfeickert
