### ISSUE TITLE
Add references about Support Vector Machine use in HEP

### ISSUE THREAD

**Issue by federicosforza** [iml-wg/HEPML-LivingReview#94]
Dear Authors,
thanks a lot for managing this really useful project!
I would like to signal the following two papers about Support Vector Machines in HEP.
If you think they are appropriate, I can open a pull request and include them in "classification" section.
Maybe these two papers (plus another one I see about SVM) can be grouped in a specific section? 
Please let me know how you prefer.

Thanks again! Best regards,
 Federico

@article{Sforza:2013hua,
    author = "Sforza, Federico and Lippi, Vittorio",
    title = "{Support vector machine classification on a biased training set: Multi-jet background rejection at hadron colliders}",
    eprint = "1407.0317",
    archivePrefix = "arXiv",
    primaryClass = "hep-ex",
    doi = "10.1016/j.nima.2013.04.046",
    journal = "Nucl. Instrum. Meth. A",
    volume = "722",
    pages = "11--19",
    year = "2013"
}

@article{Bevan:2017stx,
    author = "Bevan, Adrian and Go\~ni, Rodrigo Gamboa and Stevenson, Tom and Stevenson, Tom",
    editor = "Mount, Richard and Tull, Craig",
    title = "{Support vector machines and generalisation in HEP}",
    eprint = "1702.04686",
    archivePrefix = "arXiv",
    primaryClass = "physics.data-an",
    doi = "10.1088/1742-6596/898/7/072021",
    journal = "J. Phys. Conf. Ser.",
    volume = "898",
    number = "7",
    pages = "072021",
    year = "2017"
}

**Comment by federicosforza** [comment]
Dear @bnachman and @matthewfeickert ,
I just committed a pullrequest about this issue:
https://github.com/federicosforza/HEPML-LivingReview/pull/1

I hope I didn't do anything wrong, but please let me know otherwise and I'll try to fix it!
Thank you again for managing the project!
Cheers,
 Federico

**Comment by federicosforza** [comment]
hi @bnachman , hi @matthewfeickert ,
does the merge request look good?
Should I do something else to push it?

Thanks for the feedback, cheers,
 Federico

**Comment by matthewfeickert** [comment]
@federicosforza sorry didn't mean to be ignoring you this whole time. Let me look tonight. Am on phone atm.

**Comment by federicosforza** [comment]
> @federicosforza sorry didn't mean to be ignoring you this whole time. Let me look tonight. Am on phone atm.

hi @matthewfeickert , It come to my mind to check the status of this merge request... if there are no problem, would it be possible to merge it?
Thank you very much :)
