### ISSUE TITLE
Journal reference for preprint 2012.04595

### ISSUE THREAD

**Issue by SiLiKhon** [iml-wg/HEPML-LivingReview#95]
Hi!

Would it be possible to add the journal reference for the preprint [arXiv:2012.04595](https://arxiv.org/abs/2012.04595):

> Maevskiy, A., Ratnikov, F., Zinchenko, A. et al. Simulating the time projection chamber responses at the MPD detector using generative adversarial networks. Eur. Phys. J. C 81, 599 (2021). https://doi.org/10.1140/epjc/s10052-021-09366-4

Thanks a lot!

Best regards,
Artem

**Comment by ramonpeter** [comment]
Hi @SiLiKhon thank you for this update on this reference!
Would you be able to add this information following the instructions here: https://github.com/iml-wg/HEPML-LivingReview/blob/master/CONTRIBUTING.md? 
We are happy to help if you run into any issues.

Best,
Ramon
